### ISSUE TITLE
Qwen1.5-14B-AWQ 在相同设备下比Qwen1.5-7B慢的多？

### ISSUE THREAD

**Issue by Crayon-s7** [QwenLM/Qwen2#374]
![image](https://github.com/QwenLM/Qwen1.5/assets/72250387/e44e1dc5-7303-453b-b9a8-39b494e5d7b6)
huggingface上的代码得运行2min，而7B只需要10s左右

**Comment by jklj077** [comment]
1. Ensure you're comparing model speeds rather than elapsed time directly, considering potential variations in generated sequences.
2. Verify that your benchmarked speeds align with our published results available at <https://qwen.readthedocs.io/en/latest/benchmark/hf_infer.html>.
3. To facilitate troubleshooting, kindly provide additional details. Clarify which device settings are identical, specify the versions of CUDA, PyTorch, transformers, and auto-awq in use, and confirm whether autoawq-kernels has been correctly installed.
