### ISSUE TITLE
流式逻辑改造

### ISSUE THREAD

**Issue by summerrain321** [QwenLM/Qwen2#377]
参考文档：https://qwen.readthedocs.io/en/latest/inference/chat.html#streaming-mode
希望改成：输入参数包括history控制，类似
for response in model.chat_stream(tokenizer, _query, history=_task_history, generation_config=config):

目标：history可以在推理中途修改，干预LLM推理中途的错误结果
请问有qwen1.5有参考程序吗？

**Comment by jklj077** [comment]
Correct me if I'm mistaken, but it sounds like your scenario involves modifying previously generated tokens before proceeding with further generation. This isn't inherently about streaming generation but rather alters the typical generation workflow. The issue here is that it goes against the design of most frameworks for causal language models, which generate text sequentially (step-by-step). Replacing generated parts mid-process would necessitate retokenization and recomputation, a feature not currently supported by known frameworks.

**Comment by gg22mm** [comment]
建议搞个 惩罚机制，避免出现过的token。要不然成下面这样的了：

(mygptback) [root@localhost 千问]# python trains_desc.py 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
----查看聊天历史拼接---： <|im_start|>system
你是个乐于助人的助手<|im_end|>
<|im_start|>user
怀孕前需要到医院哪些常规检查<|im_end|>
<|im_start|>assistant

你好，怀孕前需要到医院做以下检查：1、血常规检查：血常规检查是检查孕妇血常规的常用方法，血常规检查包括血红蛋白、红细胞、白细胞、血小板、血沉、血常规、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、血型、

**Comment by jklj077** [comment]
@gg22mm Hi, your issue appears different from the original author's, and the provided models should not behave in this way. Please open a new one to describe your issue.
