### ISSUE TITLE
请教如何添加[CLS] token

### ISSUE THREAD

**Issue by wciq1208** [QwenLM/Qwen2#544]
我想添加一个下游任务，让模型对比两段文本的相似度，需要添加[CLS]来提取需要比较的两个文本的特征后计算相似度，请问如何需要如何修改配置文件呢

**Comment by jklj077** [comment]
Hi,

There are no such things as [CLS] token for Qwen or other causal language models. Here are some background information for you on why you should not use Qwen directly as embedding models.

The Qwen series are Causal Language Models (Causal LMs), as the popular GPT series opposed to the BERT series. They are primarily designed to predict the next token in a sequence given the previous tokens. It does this by learning the conditional probability distribution of the next token based on the context provided by the preceding tokens. This architecture makes it well-suited for tasks like text generation, where the model can generate coherent continuations of a given prompt.

However, using a Causal LM as an embedding model, i.e., for representing the meaning of a piece of text in a vector space, is not ideal for several reasons:

1. **Lack of Bidirectional Context**: Causal LMs only consider the context that comes before a word or phrase when generating embeddings. They do not take into account the context that follows. This means that the representation may not fully capture the meaning of a word or phrase because it does not consider how it is used in the following context.

2. **Generation Focus**: Causal LMs are optimized for generating text, which involves understanding the syntactic and semantic rules of language to produce coherent continuations. While this requires some understanding of the input text, it does not necessarily result in embeddings that accurately represent the nuanced meaning of the text for comparison purposes.

3. **Non-Optimal for Similarity**: The training objective of a Causal LM is not directly related to capturing semantic similarity between texts. Instead, its focus is on predicting the next word, which might not always align with the goal of measuring textual similarity.

Please consider using models specifically designed for this purpose, such as BERT or Sentence Transformers. These models are bidirectional and are explicitly trained on tasks that require understanding the meaning of text, making them potentially better suited for text similarity and comparison tasks.
