### ISSUE TITLE
使用M40运行Qwen2生成乱码

### ISSUE THREAD

**Issue by godcrying** [QwenLM/Qwen2#721]
我的Tesla M40显卡不支持bf16，然后使用fp16跑模型，输出会乱码。

下载了GPTQ-Int8的量化模型，用float32加载，也会输出乱码。

租用了A30跑qwen2就没有问题。

**Comment by MikeJackOne** [comment]
> 2080ti22g也跑不了bf16，但是可以跑fp16，不过我买多了一张，本来想nvlink，后面发现只能单卡跑，你需要吗？

可以考虑给我

**Comment by jklj077** [comment]
What frameworks were you using? transformers, vllm, or llama.cpp/ollama? What were your generation configs? Did you use a low temperature? What models were you using?

If generating gibberish is caused by spurious overflow or underflow, you could try the following:
- For cards with archs earlier than volta (V series) or turing (2080 series), using fp32 is the sensible option. 
- If your cards have a good support of fp16, using a different backend implementation can help, e.g., using a different framework (vllm instead of transformers+pytorch) or using a different backend (flash attention v2 instead of manual in transformers attention)
- For GPTQ-Int8 models (most likely you were still running them in fp16), consider using vllm instead of transformers+auto_gptq

**Comment by godcrying** [comment]
> What frameworks were you using? transformers, vllm, or llama.cpp/ollama? What were your generation configs? Did you use a low temperature? What models were you using?
> 
> If generating gibberish is caused by spurious overflow or underflow, you could try the following:
> 
> * For cards with archs earlier than volta (V series) or turing (2080 series), using fp32 is the sensible option.
> * If your cards have a good support of fp16, using a different backend implementation can help, e.g., using a different framework (vllm instead of transformers+pytorch) or using a different backend (flash attention v2 instead of manual in transformers attention)
> * For GPTQ-Int8 models (most likely you were still running them in fp16), consider using vllm instead of transformers+auto_gptq

感谢大佬的回复！模型使用的自带默认配置文件，没有修改。

尝试过以下方法，都会出现乱码：
1. Qwen2-7B-Instruct/Qwen2-7B-Instruct-GPTQ-Int8 使用该项目提供的推理脚本+M40显卡；
2. Qwen2-7B-Instruct/Qwen2-7B-Instruct-GPTQ-Int8 使用llamafactory项目提供推理方法+M40显卡；
3. qwen2-7b-instruct-q4_k_m.gguf 使用 llama.cpp 和笔记本 3050Ti 显卡 offload layers，**不带fa参数**；
4. Qwen2-7B-Instruct-GPTQ-Int8 修改参数以 float32 方式加载，依然会出现乱码。nvidia-smi查看显存已经占用2倍。

qwen2-7b-instruct-q4_k_m.gguf 使用 llama.cpp 和笔记本3050Ti显卡offload layers，**带fa参数**时，不会出现乱码；llama.cpp纯CPU推理也不会出现乱码。

vllm和flash-attention 显卡M40不支持，所以没有进行尝试。

**Comment by jklj077** [comment]
Hi, 

If M40 supports fp16 GEMM with fp32 accumulation (I don't think it does though), there is a slim chance you can run the original 7B model in transformers with fp16 and enforce attn_implementation="eager" with [this patch](https://github.com/jklj077/transformers/tree/qwen2-patch).

**Comment by godcrying** [comment]
@jklj077 谢谢，可以正常输出了。请问这个patch会合并到transformer主分支吗？
