### ISSUE TITLE
Qwen2-72B的max_new_token是多少

### ISSUE THREAD

**Issue by coolgxt** [QwenLM/Qwen2#748]
通过文档了解到了Qwen2-7/72B的模型支持最大128k的上下文，但是并不代表最长的输出token=128k-输入tokens，请问最长的输出token是多少？

**Comment by jklj077** [comment]
Let me explain this a litte, because it does not work as you think.

Qwen models are causal language models and it was trained by predicting the next token based on the contexts. The sequences in training consist of multiple documents and has a maximum length of 32K tokens. The length of 128K tokens is supported using YARN. 

In inference, the so called "output" is the completion or continuation of the given context and not inherently different from the "input". Techinically, there is no maximum input length or maximum output length and only maximum sequence length.

In fact, if you remove the stopping criteria in inference, the generation will continue and never stop. The text should be fluent until the maximum sequence length (or even longer since it can generalize), but it may contain multiple documents, as it is trained to do. The length of each document is determined by the model itself and not a value that can be preset. 

Therefore, techinically, the model can generate text of length up to the maximum sequence length, but the lengths of the documents contained in the sequence may vary. It could be 32 tokens or 32K tokens, depending on the context.
