### ISSUE TITLE
generate函数使用cache出错

### ISSUE THREAD

**Issue by snsun** [QwenLM/Qwen2#819]
为了缓存上下文，我在调用generate函数的时候，使用cache，return_dict_in_generate=True，但是传入cache之后，mask的形状不对。

 ```
prompt = "Give me a short introduction to large language model."
 prompt = "给我介绍一下电影《大决战》."
 
 messages = [{"role": "user", "content": prompt}]

 text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

 model_inputs = tokenizer([text], return_tensors="pt").to(device)
 output = model.generate(model_inputs.input_ids, max_new_tokens=200, do_sample=True, return_dict_in_generate=True)
 generated_ids = output.sequences
 past_key_values = output.past_key_values 
 generated_ids = [output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)]
  
 response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
 print(response)

 output = model.generate(model_inputs.input_ids, max_new_tokens=512, do_sample=True, return_dict_in_generate=True, past_key_values=past_key_values)
 generated_ids = output.sequences
 past_key_values = output.past_key_values
```

当我第二次调用的时候，mask出错，排查了一下，这里是attention_mask的问题。
https://github.com/huggingface/transformers/blob/7f5d644e69068825bb5b6e84cdc56b3d3a9bd04f/src/transformers/modeling_attn_mask_utils.py#L132
请问这里是一个bug吗

**Comment by jklj077** [comment]
Hi, 

For causal LMs like Qwen, the generation as realized by `model.generate` is an iterative process involving multiple steps until the stopping criteria are fulfilled. In each step, the full input sequence is taken by the model, which outputs the next token distribution, and in turn, the next token is sampled and appended to the input sequence. It is often known as auto-regressive generation. 

`past_key_values` caches the key and value tensors in self attention for the full input sequences in each step such that the next step does not to need to compute those tensors on the past tokens again. It is often managed by the generation procedure and is meaningful only in a single run of generation. In short, it save computation in a single run of generation.

However, there is another technique called prefix caching that aims to save computation across multiple runs of generation. It is based on the fact that in real-world scenario, the input sequences from multiple user requests may have a common prefix. Caching the key and value tensors in self attention for the prefix can save substantial computation if the prefix is sufficiently long and sufficiently common. Each item in the cache can be produced using `past_key_values`, but the caching mechanism itself is managed by the application, e.g., which prefix should be cached and when should a prefix be evicted.

Assuming your code is a part of the attempt to implementing prefix caching, the problem is that the `past_key_values` in `outputs` actually contains _future_ tokens for `model_inputs`. You could extract related parts from the `past_key_values`:

```python
prefix_key_values = tuple((k[:, :, :model_inputs.input_ids.shape[1] - 1, :], v[:, :, :model_inputs.input_ids.shape[1] - 1, :]) for k, v in outputs.past_key_values)

outputs = model.generate(**model_inputs, max_new_tokens=200, return_dict_in_generate=True, past_key_values=prefix_key_values)
```

The above is tested with `transformers==4.43.3`. Please do note that your input is too short to obtain meaningful time savings for modern GPUs.

**Comment by snsun** [comment]
Thanks for your helpful explanation. 
Yes, in my example, I want to simulate multi-turn dialog as you said. Therefore, I want to cache the key and values. 

Another related question. If I want to do multi-turn dialog, what's the prefer way？One way is caching the past_key_values outside the generate method.  Another way is appending the new question to the history conversations and calling generate again. Which one is the best way?

**Comment by jklj077** [comment]
depending on the model size and the sequence length; benchmarking is needed to determine which way is the best overall.
