### ISSUE TITLE
qwen2‘s tokenizer is very strange.

### ISSUE THREAD

**Issue by DavideHe** [QwenLM/Qwen2#834]
python code
```
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-7B",trust_remote_code=True) 
text = "<|endoftext|><s>What is an activated complex?\n\n\n</s>"
input_ids = tokenizer(text,add_special_tokens=False)["input_ids"]
tokens = tokenizer.convert_ids_to_tokens(input_ids)
print(tokens)
## result
## ['<|endoftext|>', '<s', '>', 'What', 'Ġis', 'Ġan', 'Ġactivated', 'Ġcomplex', '?ĊĊĊ', '</', 's', '>']
```
Is it char map: "Ġ" -> " ", "Ċ" -> "\n"  ?
why not just show original char with `tokenizer.convert_ids_to_tokens`

secondly,  `<s>` is in the vocabulary, why token encode to `<s` and `>`?  Does it not generate more tokens ? OR I `tokenizer` it with not good args.

**Comment by jklj077** [comment]
[the tokenizer code](https://github.com/huggingface/transformers/blob/v4.43.3/src/transformers/models/qwen2/tokenization_qwen2.py) is open and you can see it for yourself. 

basically, `transformers` requires the representation of tokens to be of type `str` (Unicode), which is not the case for Qwen that operates on UTF-8 encoded `bytes`. so there is [a bytes--to--unicode-str mapping](https://github.com/huggingface/transformers/blob/47c29ccfaf56947d845971a439cbe75a764b63d7/src/transformers/models/qwen2/tokenization_qwen2.py#L42-L65), aka, [tokenizer.byte_encoder](https://github.com/huggingface/transformers/blob/47c29ccfaf56947d845971a439cbe75a764b63d7/src/transformers/models/qwen2/tokenization_qwen2.py#L176). it is what is done in [the original gpt2 code](https://github.com/openai/gpt-2/blob/master/src/encoder.py).

> why not just show original char with tokenizer.convert_ids_to_tokens

because of the requirement in `transformers`, the reason for which is not known. my best guess is due to some historical reasons and the fact that you cannot store bytes in txt safely and in json, not at all. you will need a mapping somehow, be it base64 (which is obviously less readable) or some customized ones.

> secondly, <s> is in the vocabulary

<s> is not in the vocabulary; it never is.
